### ISSUE TITLE
code mistake？

### ISSUE THREAD

**Issue by williamdeve** [Atmosphere/atmosphere-extensions#108]
```
public Broadcaster initialize(String id, URI uri, AtmosphereConfig config) {
    super.initialize(id, URI.create("http://localhost:6379"), config);
    this.redisUtil = new RedisUtil(uri, config, new RedisUtil.Callback() {
```

Why did you use ("http://localhost:6379") instead of URI  in super initialization?

**Comment by christianHennig** [comment]
I think the bug is not fixed:
https://github.com/Atmosphere/atmosphere-extensions/blob/master/redis/modules/src/main/java/org/atmosphere/plugin/redis/RedisBroadcaster.java#L42
