### ISSUE TITLE
Can't compile atmosphere module in GWT2.7

### ISSUE THREAD

**Issue by kasas** [Atmosphere/atmosphere-extensions#169]
Hi guys,

I have upgraded atmosphere to the new version of GWT, however when I try to compile it throws this error:

Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
         [ERROR] Errors in 'org/atmosphere/gwt20/client/AutoBeanClientSerializer.java'
            [ERROR] Line 85: Only class literals may be used as arguments to GWT.create()
         Unification traversed 36046 fields and methods and 2940 types. 2896 are considered part of the current module and 2896 had all of their fields and methods traversed.
      [ERROR] Compiler returned false

Any help? I've been looking for the error but I haven't found anything yet

Cheers

**Comment by jfarcand** [comment]
Please use this branch: https://github.com/Atmosphere/atmosphere-extensions/tree/extensions-2.2.x-gwt-2.7

**Comment by kasas** [comment]
I am using this branch, the problem came when I use this code:

			AutoBeanClientSerializer json_serializer = new AutoBeanClientSerializer();
			json_serializer.registerBeanFactory(beanFactory,
					IAtmosphereMessage.class);

when connecting to Atmosphere. It did work in other versions, I don't kwno why it is not working in the new version. The error keep saying:

 [ERROR] Errors in 'org/atmosphere/gwt20/client/AutoBeanClientSerializer.java'
            [ERROR] Line 85: Only class literals may be used as arguments to GWT.create()

**Comment by michaelwiles** [comment]
Same with me... can't see how we can get around this as as far as I understand it's a GWT limitation. 

I suspect the solution is to remove the method altogether. It is not mandatory as it is a utility method (it simply calls the "other"  method).

**Comment by kasas** [comment]
At the end it was a problem with the interface I implemented. Be sure to put all get and set methods.

**Comment by jfarcand** [comment]
@kasas @michaelwiles OK so please confirm everything is properly working. I will cut an official release this week.

**Comment by kasas** [comment]
I am using atmosphere in my project without any trouble using the last version. However it would be great that de GWT module incorporates the js files in order to have everything together like in other modules.

**Comment by jfarcand** [comment]
@kasas Contribution welcomed :-)

**Comment by kasas** [comment]
@jfarcand when I have time I'll try to contribute ;)

**Comment by rabbitfr** [comment]
Still not working
