### ISSUE TITLE
SocketIO Extension example

### ISSUE THREAD

**Issue by santiagopoli** [Atmosphere/atmosphere-extensions#176]
Can someone give me an example about how to use the SocketIO extension for Atmosphere?
I tried to follow this example https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-Socket.IO but it seems outdated (and doesn't use the extension at all).

**Comment by jfarcand** [comment]
@santiagopoli Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1
