### ISSUE TITLE
atmosphere-gwt doesn't work together with MessageSize tracking

### ISSUE THREAD

**Issue by robert7k** [Atmosphere/atmosphere-extensions#195]
Enabling MessageSizeTracking on the client (by setting HTTP header `X-Atmosphere-TrackMessageSize` or setting the flag `AtmosphereRequestConfig.Flags.trackMessageLength`) is useless because the server cannot create valid messages.

Using `TrackMessageSizeFilter` is also useless together with atmosphere-gwt because it only supports Strings as messages.

**Comment by jfarcand** [comment]
Not sure what you are doing, but it do work with one of the sample:

https://goo.gl/RFJH57

**Comment by jfarcand** [comment]
Ok just saw you pull request. Please gives more information and also try to reproduce with the sample so I can understand why you think it doesn't work :-)

**Comment by robert7k** [comment]
The sample you linked to works because it only transmits `String`s, which can be handled by `TrackMessageSizeFilter`.

Transmitting POJOs serialized by `GwtRpcSerializer` (the default serializer) fails when message size tracking is enabled.

Code example for serializing (MyMessage is a simple `Serializable` class with one field):

     MyMessage msg = new MyMessage ("hi");
     final Broadcaster bc = broadcasterFactory.lookup(channel, false);
     bc.broadcast(msg);

The linked pull request fixes the problem

**Comment by robert7k** [comment]
Here's a patch to the sample which clarifies what I mean: 
https://github.com/robert7k/atmosphere-samples/commit/9d66326f837eae7766bcebefc4e45de679973e26

**Comment by jfarcand** [comment]
@robert7k This break all the existing samples (just found the time to test it). Will need to rollback.
