### ISSUE TITLE
The implementation of SockJS protocol is not right

### ISSUE THREAD

**Issue by jccampanero** [Atmosphere/atmosphere-extensions#223]
It seems the implementation provided for the SockJS protocol is not correct. The method ```inspect``` defined in ```SockJsAtmosphereInterceptor``` doesn´t handle the right token positions defined by SockJS as explained in [https://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html#section-36](sockjs protocol).

References pull request #224.

**Comment by elakito** [comment]
@jccampanero i don't know why the wrong index was used before.
we can apply your patch for the index part, but for the param method should be better replaced with something like 
String[] params(String url, int pos) to return the params up to the pos-th position at once so that we don't need to call param(..., 2) and param(.., 3) and run the split twice. Here, I think, it is also simpler to iterate over indexOf('/') to pick the first pos params.

**Comment by jccampanero** [comment]
@elakito Sorry for the long time in reply.

I have pushed a new version of the code with the changes you indicated to me.

In this code you can see that I raise different validation, non expected, exceptions : please , I'd appreciate if you could verify that it does not break the logic followed by the rest of interceptors.

Feel free to ask me for any suggestions or improvements if appropiate.

**Comment by elakito** [comment]
@jccampanero somehow the diff is showing the entire file to be different from its parent and there are two such commits in this PR. That makes it difficult to see what has changed. If you could create a single commit file that only includes the relevant diff, that would be appreciated.
thanks.
regards, aki

**Comment by jccampanero** [comment]
@elakito you are right, I'm sorry, I did my changes in a windows system and it changed line endings.
I have rewrited our commit history: please, can you verify if the pull request is right now?
Thank you very much.
Regards,
J. Carlos

**Comment by elakito** [comment]
@jccampanero thanks. 
I have merged your PR with a slight change.
regards, aki

**Comment by jccampanero** [comment]
@elakito Please, excuse my delay in reply.

Thank you very much for merge our changes in your library. 

Thank you very much for your job and for your great library Aki.

Kind regards,
J. Carlos

**Comment by elakito** [comment]
@jccampanero atmosphere is a community supported project and we thank you for your valuable contribution ;-)
regards, aki
