### ISSUE TITLE
Next release eta?

### ISSUE THREAD

**Issue by carlislefox** [Atmosphere/atmosphere-extensions#237]
Hey guys can we push another release out?

I really need the fix from #235 available in maven and for some reason despite it's merge in April it didn't make it into May's 2.4.4 release.

**Comment by jfarcand** [comment]
@carlislefox will cut it later today. Stay tuned!

**Comment by carlislefox** [comment]
Thank you very much man.

**Comment by jfarcand** [comment]
Done!

**Comment by sergeyklay** [comment]
Could be closed?
