### ISSUE TITLE
WebLogic not supporting more parallel connections from IE or Edge

### ISSUE THREAD

**Issue by jpomac** [Atmosphere/atmosphere-extensions#242]
Configuration:
  Oracle WebLogic server 10.3.6
  atmosphere-extensions-project ver. 2.4.22-SNAPSHOT
  atmosphere-runtime ver. 2.4.32
  atmosphere-javascript ver. 2.3.8

If end user calling atmosphere framework on WebLogic server from IE or Edge, the connection use long-polling transport and next connection break previouse working connection. This issue is due to AtmosphereWebLogicServlet associate RequestResponseKey on http session that is shared by all browser windows/tabs and every new connection overwrite previouse RequestResponseKey.

**Comment by jfarcand** [comment]
@jpomac Can you do a pull request? This is much simple to merge and also I will be able to cut an official release. Thanks!!!

**Comment by jpomac** [comment]
@jfarcand Sorry, I don't understand to your question "Can you do a pull request?". What request do you mean? Thanks.

**Comment by jfarcand** [comment]
See https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by jpomac** [comment]
The #243 resolve problem by storing RequestResponseKey in conjunction with tracking ID and seems that is working correctly now.
