### ISSUE TITLE
SocketIOAtmosphereInterceptor::inspect gets confused with wildcard and deep paths

### ISSUE THREAD

**Issue by treyhyde** [Atmosphere/atmosphere-extensions#63]
It splits the path on / and assumes index 0 is the version and index 1 is the protocol.

If you set up a resource path like /a/foo/123 (and map Atmosphere with a path like /a/foo/* ) socket.io will convert that to /a/foo/123/1/websockets.   This has resulted in exceptions like "Protocol not supported : 1" which wasn't entirely clear to me what was wrong (until I read the code).

**Comment by ecamaj** [comment]
I'm trying to understand this, I get same error, but seems that URL of socket.io requests has changed?
I have no slashes ("/") in request, I have get parameters ("/?EIO=3&transport=polling&t=Lo1WRIr") and SocketIOAtmosphereInterceptor expects slashes. I am doing something wrong or this has changed?

**Comment by jfarcand** [comment]
@ecamaj This module is out of date and need some works...contribution welcomed!
